### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Johncheng1** [jinglou/p2016-rss-small-target#1]
can you tell me how to run this project,that can get the result in your paper?

**Comment by jinglou** [comment]
If you want to get the detection results of RSS, you can download [RSS.zip](https://raw.githubusercontent.com/jinglou/p2016-rss-small-target/master/RSS.zip) and run **Demo.m**. 
Please see **README** in https://github.com/jinglou/p2016-rss-small-target/tree/master/RSS

**Comment by Johncheng1** [comment]
你好，请问为什么我运行那个demo后没有任何反应呢，谢谢

**Comment by Johncheng1** [comment]
会生成一个文件夹，然后下面有三个文件夹，文件夹里面是空的，谢谢

**Comment by jinglou** [comment]
你好。我刚才下载了RSS.zip，并使用R2014b和R2017a两个版本的MATLAB都试了一下，没有发现问题。
你可以取消注释DEMO.m中的如下代码：

> figure(1);
subplot(221),imshow(rgb),title(['# ',int2str(imgno)]);
subplot(222),imshow(labeltarget(rgb,Targets));
subplot(223),imshow(StabilityMap);
subplot(224),imshow(SaliencyMap);
pause(0.01);

会实时显示检测结果。

**Comment by Johncheng1** [comment]
谢谢，刚才跑通了，是data的路径没有写一下，谢谢

**Comment by jinglou** [comment]
不客气，感谢关注我们的工作。

**Comment by Johncheng1** [comment]
你好，我看您的论文里面有一个评价指标公式，在您的程序中是哪一个文件呢?谢谢
![qq 20171101170328](https://user-images.githubusercontent.com/25736763/32267737-3afef1a0-bf27-11e7-9c6f-61ede0062cac.jpg)
![qq 20171101170342](https://user-images.githubusercontent.com/25736763/32267738-3b4d20be-bf27-11e7-866b-2e4bb8dcd033.jpg)

**Comment by jinglou** [comment]
您好，这是显著性中经典的指标计算公式，仓库中并未给出对应的代码。
我们计划在[CNS论文](https://github.com/jinglou/p2017-cns-sod)被录用之后，将指标计算代码和绘图代码一并发布，具体时间未定。

**Comment by Johncheng1** [comment]
好的，谢谢

**Comment by Johncheng1** [comment]
您好     我正在阅读您的p2016-rss-small-target   matlab源码    demo中提到    σ= min（W，H）/σs   请问参数σ和σs 代表什么意思，取min（W，H）来做自适应的高斯滤波窗口有何意义，与固定窗口比较，优势在哪里？ 谢谢！

**Comment by jinglou** [comment]
σ是高斯滤波器的标准差，窗口大小直接选为3倍的σ，故这里只需要确定σ。
从理论上来说，要想凸显小的目标区域，应选用一个较大的σ。实事求是的说，我们并没有过多地考虑窗口的优势问题，而且一开始就没考虑过固定窗口。只是觉得数据集1中有较大的目标尺寸变化，故想通过图像大小+一个可调的控制参数(即σs)来得到自适应的σ。重点在于：
1) 本文是显著性在目标检测上的一个应用，即作为辅助手段，看能否在稳定性方法(MSER或RSt)的基础上借助显著性来剔除虚警。文中的显著性方法只是简单的对FT方法做了下改造，从度量全局稀缺性->度量局部差异性，以此来凸显小的局部区域。我们并没有对显著性模块精心设计算法。
2) 因此，用min或者max都没关系(至多只是调参得到的σs不同)。固定窗口也没有关系，只要有合适的固定窗口能够凸显小目标区域的同时抑制图像背景。甚至在实验评估部分也可以看到，通过其它显著性方法，也可以改善稳定性方法的检测性能。

**Comment by Johncheng1** [comment]
谢谢您的讲解
